#!/bin/sh
chmod 755 /etc/init.d/speedtest /etc/init.d/speedtest >/dev/null 2>&1
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@speedtest[-1]
	add ucitrack speedtest
	set ucitrack.@speedtest[-1].init=speedtest
	commit ucitrack
EOF
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*
exit 0
